exportconst FETCH_WORKSHOPS = 'FETCH_WORKSHOPS';
exportconst FETCH_WORKSHOPS_SUCCESS = 'FETCH_WORKSHOPS_SUCCESS';
exportconst FETCH_WORKSHOPS_FAILURE = 'FETCH_WORKSHOPS_FAILURE';
exportconst CREATE_WORKSHOP = 'CREATE_WORKSHOP';
exportconst CREATE_WORKSHOP_SUCCESS = 'CREATE_WORKSHOP_SUCCESS';
exportconst CREATE_WORKSHOP_FAILURE = 'CREATE_WORKSHOP_FAILURE';