export const FETCH_WORKSHOPS = 'FETCH_WORKSHOPS';
export const FETCH_WORKSHOPS_SUCCESS = 'FETCH_WORKSHOPS_SUCCESS';
export const FETCH_WORKSHOPS_FAILURE = 'FETCH_WORKSHOPS_FAILURE';
export const CREATE_WORKSHOP = 'CREATE_WORKSHOP';
export const CREATE_WORKSHOP_SUCCESS = 'CREATE_WORKSHOP_SUCCESS';
export const CREATE_WORKSHOP_FAILURE = 'CREATE_WORKSHOP_FAILURE';